services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:ro
      - /app/.venv
    # Add any environment variables here, if necessary. Example:
    # environment:
    #   - DATABASE_URL=your_database_url
    #   - SECRET_KEY=your_django_secret_key
    # depends_on:
    #   - db
