services:
  backend:
    build:
      context: ./django-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # volumes:
    #   - ./django-api:/app
    # environment:
    #   - DEBUG=1
    #   - SECRET_KEY=your_development_secret_key # Use a secure key for production
    #   - DATABASE_URL=...
    # command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    # volumes:
    #   - ./frontend/src:/app/src
    #   - ./frontend/public:/app/public
    # environment:
    #   - REACT_APP_API_URL=http://backend:8000/api
    depends_on:
      - backend
    # command: npm start